version: '3.8'

services:
  web:
    image: admin-app:${APP_VERSION}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
